# Generated by Django 4.0.2 on 2022-02-21 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('confirmation_number', models.CharField(max_length=50)),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.stop')),
            ],
        ),
    ]
